### ISSUE TITLE
Build: meson option(s) for the tests

### ISSUE THREAD

**Issue by swilmet** [gedit-technology/libgedit-gfls#2]
commit 2ddc20a52645aae686093bb7aae0abf75aa9de22 added the `tests` meson option.

Usually in the projects that I develop, the tests are always built because they don't depend on more deps.

Here there is the gtk3 dep that is not necessary for the library, just for certain interactive test(s).

Also usually I don't like automagic behavior by the build system.

So an idea is to have just a `gtk3_tests` meson option. false by default so the module is easier to package. When true, gtk3 is required and the relevant interactive test(s) are built. When false it doesn't even check for gtk3 existence in order to avoid automagic behavior.

**Comment by Biswa96** [comment]
I prefer an option to disable all tests. For example,
* gtk https://gitlab.gnome.org/GNOME/gtk/-/blob/4.14.4/meson_options.txt?ref_type=tags#L152
* glib https://gitlab.gnome.org/GNOME/glib/-/blob/2.80.2/meson_options.txt?ref_type=tags#L93
* libadwaita https://gitlab.gnome.org/GNOME/libadwaita/-/blob/1.5.1/meson_options.txt?ref_type=tags#L16

I would like the same tests option for other gedit projects also.

**Comment by swilmet** [comment]
Makes sense, it is a legitimate request. It gives faster builds in case the tests aren't needed, and fewer build failures in case a test file doesn't compile on some platform.

**Comment by swilmet** [comment]
Since there is now the `tests` meson option, adding `gtk3_tests` would make things a bit overloaded. So it's good enough as it is.

The same can be done in the other gedit repos.
